basePath: /api
definitions:
  auth.ConfirmEmailRequest:
    properties:
      code:
        example: "123456"
        type: string
      email:
        example: user@example.com
        type: string
    required:
    - code
    - email
    type: object
  auth.ConfirmEmailResponse:
    properties:
      message:
        example: Email успешно подтвержден
        type: string
    type: object
  auth.RefreshRequest:
    properties:
      refresh_token:
        example: <refresh_token>
        type: string
    required:
    - refresh_token
    type: object
  auth.RefreshResponse:
    properties:
      access_token:
        example: <access_token>
        type: string
      refresh_token:
        example: <refresh_token>
        type: string
    type: object
  auth.SignInRequest:
    properties:
      email:
        example: user@example.com
        type: string
      password:
        example: password123
        type: string
    required:
    - email
    - password
    type: object
  auth.SignInResponse:
    properties:
      tokens:
        $ref: '#/definitions/entities.Tokens'
      user:
        $ref: '#/definitions/auth.SignUpResponse'
    type: object
  auth.SignUpRequest:
    properties:
      email:
        example: user@example.com
        type: string
      password:
        example: password123
        minLength: 8
        type: string
    required:
    - email
    - password
    type: object
  auth.SignUpResponse:
    properties:
      created_at:
        example: "2023-01-01T00:00:00Z"
        type: string
      email:
        example: user@example.com
        type: string
      id:
        example: 123
        type: integer
      updated_at:
        example: "2023-01-01T00:00:00Z"
        type: string
      verified_at:
        example: false
        type: boolean
    type: object
  auth.VerifyEmailRequest:
    properties:
      email:
        example: user@example.com
        type: string
    required:
    - email
    type: object
  auth.VerifyEmailResponse:
    properties:
      message:
        example: Email успешно отправлен
        type: string
    type: object
  entities.Tokens:
    properties:
      accessToken:
        type: string
      refreshToken:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@imperial.com
    name: API Support
  description: REST API для проекта Imperial
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: Imperial API
  version: "1.0"
paths:
  /v1/auth/confirm-email:
    post:
      consumes:
      - application/json
      description: Подтверждение кода
      parameters:
      - description: Email для отправки кода верификации
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/auth.ConfirmEmailRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Email успешно отправлен
          schema:
            $ref: '#/definitions/auth.ConfirmEmailResponse'
      summary: Подтверждение кода верификации на email
      tags:
      - auth
  /v1/auth/refresh-token:
    post:
      consumes:
      - application/json
      description: Обновляет access токен с помощью refresh токена
      parameters:
      - description: Данные для обновления токена
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/auth.RefreshRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Токен успешно обновлен
          schema:
            $ref: '#/definitions/auth.RefreshResponse'
      summary: Обновление access токена
      tags:
      - auth
  /v1/auth/sign-in:
    post:
      consumes:
      - application/json
      description: Аутентификация пользователя с помощью email и пароля
      parameters:
      - description: Данные для входа
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/auth.SignInRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Пользователь успешно аутентифицирован
          schema:
            $ref: '#/definitions/auth.SignInResponse'
      summary: Вход пользователя
      tags:
      - auth
  /v1/auth/sign-up:
    post:
      consumes:
      - application/json
      description: Создает нового пользователя с указанным email и паролем
      parameters:
      - description: Данные для регистрации
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/auth.SignUpRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Пользователь успешно зарегистрирован
          schema:
            $ref: '#/definitions/auth.SignUpResponse'
      summary: Регистрация нового пользователя
      tags:
      - auth
  /v1/auth/verify-email:
    post:
      consumes:
      - application/json
      description: Отправляет код верификации на указанный email
      parameters:
      - description: Email для отправки кода верификации
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/auth.VerifyEmailRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Email успешно отправлен
          schema:
            $ref: '#/definitions/auth.VerifyEmailResponse'
      summary: Отправка кода верификации на email
      tags:
      - auth
securityDefinitions:
  BearerAuth:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
