basePath: /api
definitions:
  auth.ConfirmEmailRequest:
    properties:
      code:
        example: "123456"
        type: string
      email:
        example: user@example.com
        type: string
    required:
    - code
    - email
    type: object
  auth.ConfirmEmailResponse:
    properties:
      message:
        example: Email успешно подтвержден
        type: string
    type: object
  auth.RefreshRequest:
    properties:
      refresh_token:
        example: <refresh_token>
        type: string
    required:
    - refresh_token
    type: object
  auth.RefreshResponse:
    properties:
      access_token:
        example: <access_token>
        type: string
      refresh_token:
        example: <refresh_token>
        type: string
    type: object
  auth.SignInRequest:
    properties:
      email:
        example: user@example.com
        type: string
      password:
        example: password123
        type: string
    required:
    - email
    - password
    type: object
  auth.SignInResponse:
    properties:
      tokens:
        $ref: '#/definitions/entities.Tokens'
      user:
        $ref: '#/definitions/auth.SignUpResponse'
    type: object
  auth.SignUpRequest:
    properties:
      email:
        example: user@example.com
        type: string
      password:
        example: password123
        minLength: 8
        type: string
    required:
    - email
    - password
    type: object
  auth.SignUpResponse:
    properties:
      created_at:
        example: "2023-01-01T00:00:00Z"
        type: string
      email:
        example: user@example.com
        type: string
      id:
        example: 123
        type: integer
      is_verified:
        example: false
        type: boolean
      updated_at:
        example: "2023-01-01T00:00:00Z"
        type: string
    type: object
  auth.VerifyEmailRequest:
    properties:
      email:
        example: user@example.com
        type: string
    required:
    - email
    type: object
  auth.VerifyEmailResponse:
    properties:
      message:
        example: Email успешно отправлен
        type: string
    type: object
  car.CarResponse:
    properties:
      categoryId:
        type: integer
      createdAt:
        type: string
      id:
        type: integer
      imageUrl:
        type: string
      markId:
        type: integer
      name:
        type: string
      onlyWithDriver:
        type: boolean
      pricePerDay:
        type: integer
      tagsIds:
        items:
          type: integer
        type: array
      updatedAt:
        type: string
    type: object
  car.CreateCarRequest:
    properties:
      category_id:
        example: 2
        type: integer
      image_url:
        example: https://example.com/car.jpg
        type: string
      mark_id:
        example: 1
        type: integer
      name:
        example: Toyota
        type: string
      only_with_driver:
        example: false
        type: boolean
      price_per_day:
        example: 100
        type: integer
      tags_ids:
        items:
          type: integer
        type: array
    required:
    - category_id
    - image_url
    - mark_id
    - name
    - only_with_driver
    - price_per_day
    - tags_ids
    type: object
  entities.Tokens:
    properties:
      accessToken:
        type: string
      refreshToken:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@imperial.com
    name: API Support
  description: REST API для проекта Imperial
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: Imperial API
  version: "1.0"
paths:
  /v1/auth/confirm-email:
    post:
      consumes:
      - application/json
      description: Подтверждение кода
      parameters:
      - description: Email для отправки кода верификации
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/auth.ConfirmEmailRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Email успешно отправлен
          schema:
            $ref: '#/definitions/auth.ConfirmEmailResponse'
      summary: Подтверждение кода верификации на email
      tags:
      - auth
  /v1/auth/refresh-token:
    post:
      consumes:
      - application/json
      description: Обновляет access токен с помощью refresh токена
      parameters:
      - description: Данные для обновления токена
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/auth.RefreshRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Токен успешно обновлен
          schema:
            $ref: '#/definitions/auth.RefreshResponse'
      summary: Обновление access токена
      tags:
      - auth
  /v1/auth/sign-in:
    post:
      consumes:
      - application/json
      description: Аутентификация пользователя с помощью email и пароля
      parameters:
      - description: Данные для входа
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/auth.SignInRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Пользователь успешно аутентифицирован
          schema:
            $ref: '#/definitions/auth.SignInResponse'
      summary: Вход пользователя
      tags:
      - auth
  /v1/auth/sign-up:
    post:
      consumes:
      - application/json
      description: Создает нового пользователя с указанным email и паролем
      parameters:
      - description: Данные для регистрации
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/auth.SignUpRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Пользователь успешно зарегистрирован
          schema:
            $ref: '#/definitions/auth.SignUpResponse'
      summary: Регистрация нового пользователя
      tags:
      - auth
  /v1/auth/verify-email:
    post:
      consumes:
      - application/json
      description: Отправляет код верификации на указанный email
      parameters:
      - description: Email для отправки кода верификации
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/auth.VerifyEmailRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Email успешно отправлен
          schema:
            $ref: '#/definitions/auth.VerifyEmailResponse'
      summary: Отправка кода верификации на email
      tags:
      - auth
  /v1/cars:
    post:
      consumes:
      - application/json
      description: Создает новый автомобиль с указанными параметрами
      parameters:
      - description: Данные для создания автомобиля
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/car.CreateCarRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Автомобиль успешно создан
          schema:
            $ref: '#/definitions/car.CarResponse'
      security:
      - BearerAuth: []
      summary: Создание нового автомобиля
      tags:
      - cars
securityDefinitions:
  BearerAuth:
    description: 'JWT token must be passed with `Bearer ` prefix. Example: "Bearer
      eyJhbGciOiJIUzI1NiI..."'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
